const LOG_INCOMING_DELTA = process.env.LOG_INCOMING_DELTA || true;
const LOG_OUTGOING_DELTA = process.env.LOG_OUTGOING_DELTA || true;
const DELTA_INTERVAL = process.env.DELTA_INTERVAL_MS || 1000;
const LOG_DELTA_REWRITE = process.env.LOG_DELTA_REWRITE || true;

export {
  LOG_INCOMING_DELTA,
  LOG_OUTGOING_DELTA,
  DELTA_INTERVAL,
  LOG_DELTA_REWRITE
}
